/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jeidee_glooxforandroid_MsgClient_ConnectState */

#ifndef _Included_com_jeidee_glooxforandroid_MsgClient_ConnectState
#define _Included_com_jeidee_glooxforandroid_MsgClient_ConnectState
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
