/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jeidee_glooxforandroid_MsgClient */

#ifndef _Included_com_jeidee_glooxforandroid_MsgClient
#define _Included_com_jeidee_glooxforandroid_MsgClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jeidee_glooxforandroid_MsgClient
 * Method:    _newInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jeidee_glooxforandroid_MsgClient__1newInstance
  (JNIEnv *, jobject);

/*
 * Class:     com_jeidee_glooxforandroid_MsgClient
 * Method:    _connect
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jeidee_glooxforandroid_MsgClient__1connect
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jint);

/*
 * Class:     com_jeidee_glooxforandroid_MsgClient
 * Method:    _disConnect
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jeidee_glooxforandroid_MsgClient__1disConnect
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jeidee_glooxforandroid_MsgClient
 * Method:    _recv
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jeidee_glooxforandroid_MsgClient__1recv
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jeidee_glooxforandroid_MsgClient
 * Method:    _deleteInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jeidee_glooxforandroid_MsgClient__1deleteInstance
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
