/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jeidee_glooxforandroid_NativeCall */

#ifndef _Included_com_jeidee_glooxforandroid_NativeCall
#define _Included_com_jeidee_glooxforandroid_NativeCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jeidee_glooxforandroid_NativeCall
 * Method:    connectTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jeidee_glooxforandroid_NativeCall_connectTest
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
